track_parcel:
  fields:
    tracking_code:
      required: true
      example: "RR123456789SK"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "RR123456789SK"
      selector:
        text:
